export const sortCards = {
  1: {
    id: 1,
    gameName: "sort",
    type: "date",
    data: { dataId: 1, date: "1950", text: "0" },
  },
  2: {
    id: 2,
    gameName: "sort",
    type: "date",
    data: { dataId: 2, date: "1951", text: "1" },
  },
  3: {
    id: 3,
    gameName: "sort",
    type: "date",
    data: { dataId: 3, date: "1952", text: "1" },
  },
  4: {
    id: 4,
    gameName: "sort",
    type: "date",
    data: { dataId: 4, date: "1953", text: "2" },
  },
  5: {
    id: 5,
    gameName: "sort",
    type: "date",
    data: { dataId: 5, date: "1954", text: "2" },
  },
  6: {
    id: 6,
    gameName: "sort",
    type: "date",
    data: { dataId: 6, date: "1955", text: "3" },
  },
  7: {
    id: 7,
    gameName: "sort",
    type: "date",
    data: { dataId: 7, date: "1956", text: "3" },
  },
  8: {
    id: 8,
    gameName: "sort",
    type: "date",
    data: { dataId: 8, date: "1957", text: "4" },
  },
  9: {
    id: 9,
    gameName: "sort",
    type: "date",
    data: { dataId: 9, date: "1958", text: "4" },
  },
  10: {
    id: 10,
    gameName: "sort",
    type: "date",
    data: { dataId: 10, date: "1959", text: "5" },
  },
  11: {
    id: 11,
    gameName: "sort",
    type: "date",
    data: { dataId: 11, date: "1960", text: "5" },
  },
  12: {
    id: 12,
    gameName: "sort",
    type: "date",
    data: { dataId: 12, date: "1961", text: "6" },
  },
  13: {
    id: 13,
    gameName: "sort",
    type: "date",
    data: { dataId: 13, date: "1962", text: "6" },
  },
  14: {
    id: 14,
    gameName: "sort",
    type: "date",
    data: { dataId: 14, date: "1963", text: "7" },
  },
  15: {
    id: 15,
    gameName: "sort",
    type: "date",
    data: { dataId: 15, date: "1964", text: "7" },
  },
  16: {
    id: 16,
    gameName: "sort",
    type: "date",
    data: { dataId: 16, date: "1965", text: "8" },
  },
  17: {
    id: 17,
    gameName: "sort",
    type: "date",
    data: { dataId: 17, date: "1966", text: "8" },
  },
  18: {
    id: 18,
    gameName: "sort",
    type: "date",
    data: { dataId: 18, date: "1967", text: "9" },
  },
  19: {
    id: 19,
    gameName: "sort",
    type: "date",
    data: { dataId: 19, date: "1968", text: "9" },
  },

  20: {
    id: 20,
    gameName: "sort",
    type: "date",
    data: { dataId: 20, date: "1969", text: "0" },
  },
  21: {
    id: 21,
    gameName: "sort",
    type: "date",
    data: { dataId: 21, date: "1970", text: "1" },
  },
  22: {
    id: 22,
    gameName: "sort",
    type: "date",
    data: { dataId: 22, date: "1971", text: "1" },
  },
  23: {
    id: 23,
    gameName: "sort",
    type: "date",
    data: { dataId: 23, date: "1972", text: "2" },
  },
  24: {
    id: 24,
    gameName: "sort",
    type: "date",
    data: { dataId: 24, date: "1973", text: "2" },
  },
  25: {
    id: 25,
    gameName: "sort",
    type: "date",
    data: { dataId: 25, date: "1974", text: "3" },
  },
  26: {
    id: 26,
    gameName: "sort",
    type: "date",
    data: { dataId: 26, date: "1975", text: "3" },
  },
  27: {
    id: 27,
    gameName: "sort",
    type: "date",
    data: { dataId: 27, date: "1976", text: "4" },
  },
  28: {
    id: 28,
    gameName: "sort",
    type: "date",
    data: { dataId: 28, date: "1977", text: "4" },
  },
  29: {
    id: 29,
    gameName: "sort",
    type: "date",
    data: { dataId: 29, date: "1978", text: "5" },
  },
  30: {
    id: 30,
    gameName: "sort",
    type: "date",
    data: { dataId: 30, date: "1979", text: "5" },
  },
  31: {
    id: 31,
    gameName: "sort",
    type: "date",
    data: { dataId: 31, date: "1980", text: "6" },
  },
  32: {
    id: 32,
    gameName: "sort",
    type: "date",
    data: { dataId: 32, date: "1981", text: "6" },
  },
  33: {
    id: 33,
    gameName: "sort",
    type: "date",
    data: { dataId: 33, date: "1982", text: "7" },
  },
  34: {
    id: 34,
    gameName: "sort",
    type: "date",
    data: { dataId: 34, date: "1983", text: "7" },
  },
  35: {
    id: 35,
    gameName: "sort",
    type: "date",
    data: { dataId: 35, date: "1984", text: "8" },
  },
  36: {
    id: 36,
    gameName: "sort",
    type: "date",
    data: { dataId: 36, date: "1985", text: "8" },
  },
  37: {
    id: 37,
    gameName: "sort",
    type: "date",
    data: { dataId: 37, date: "1986", text: "9" },
  },
  38: {
    id: 38,
    gameName: "sort",
    type: "date",
    data: { dataId: 38, date: "1987", text: "9" },
  },

  39: {
    id: 39,
    gameName: "sort",
    type: "date",
    data: { dataId: 39, date: "1988", text: "0" },
  },
  40: {
    id: 40,
    gameName: "sort",
    type: "date",
    data: { dataId: 40, date: "1989", text: "1" },
  },
  41: {
    id: 41,
    gameName: "sort",
    type: "date",
    data: { dataId: 41, date: "1990", text: "1" },
  },
  42: {
    id: 42,
    gameName: "sort",
    type: "date",
    data: { dataId: 42, date: "1991", text: "2" },
  },
  43: {
    id: 43,
    gameName: "sort",
    type: "date",
    data: { dataId: 43, date: "1992", text: "2" },
  },
  44: {
    id: 44,
    gameName: "sort",
    type: "date",
    data: { dataId: 44, date: "1993", text: "3" },
  },
  45: {
    id: 45,
    gameName: "sort",
    type: "date",
    data: { dataId: 45, date: "1994", text: "3" },
  },
  46: {
    id: 46,
    gameName: "sort",
    type: "date",
    data: { dataId: 46, date: "1995", text: "4" },
  },
  47: {
    id: 47,
    gameName: "sort",
    type: "date",
    data: { dataId: 47, date: "1996", text: "4" },
  },
  48: {
    id: 48,
    gameName: "sort",
    type: "date",
    data: { dataId: 48, date: "1997", text: "5" },
  },
  49: {
    id: 49,
    gameName: "sort",
    type: "date",
    data: { dataId: 49, date: "1998", text: "5" },
  },
  50: {
    id: 50,
    gameName: "sort",
    type: "date",
    data: { dataId: 50, date: "1999", text: "6" },
  },
};
