export const unoCards = {
  1: {
    id: 1,
    gameName: "uno",
    type: "number",
    data: { dataId: 1, color: "red", text: "0" },
  },
  2: {
    id: 2,
    gameName: "uno",
    type: "number",
    data: { dataId: 2, color: "red", text: "1" },
  },
  3: {
    id: 3,
    gameName: "uno",
    type: "number",
    data: { dataId: 3, color: "red", text: "1" },
  },
  4: {
    id: 4,
    gameName: "uno",
    type: "number",
    data: { dataId: 4, color: "red", text: "2" },
  },
  5: {
    id: 5,
    gameName: "uno",
    type: "number",
    data: { dataId: 5, color: "red", text: "2" },
  },
  6: {
    id: 6,
    gameName: "uno",
    type: "number",
    data: { dataId: 6, color: "red", text: "3" },
  },
  7: {
    id: 7,
    gameName: "uno",
    type: "number",
    data: { dataId: 7, color: "red", text: "3" },
  },
  8: {
    id: 8,
    gameName: "uno",
    type: "number",
    data: { dataId: 8, color: "red", text: "4" },
  },
  9: {
    id: 9,
    gameName: "uno",
    type: "number",
    data: { dataId: 9, color: "red", text: "4" },
  },
  10: {
    id: 10,
    gameName: "uno",
    type: "number",
    data: { dataId: 10, color: "red", text: "5" },
  },
  11: {
    id: 11,
    gameName: "uno",
    type: "number",
    data: { dataId: 11, color: "red", text: "5" },
  },
  12: {
    id: 12,
    gameName: "uno",
    type: "number",
    data: { dataId: 12, color: "red", text: "6" },
  },
  13: {
    id: 13,
    gameName: "uno",
    type: "number",
    data: { dataId: 13, color: "red", text: "6" },
  },
  14: {
    id: 14,
    gameName: "uno",
    type: "number",
    data: { dataId: 14, color: "red", text: "7" },
  },
  15: {
    id: 15,
    gameName: "uno",
    type: "number",
    data: { dataId: 15, color: "red", text: "7" },
  },
  16: {
    id: 16,
    gameName: "uno",
    type: "number",
    data: { dataId: 16, color: "red", text: "8" },
  },
  17: {
    id: 17,
    gameName: "uno",
    type: "number",
    data: { dataId: 17, color: "red", text: "8" },
  },
  18: {
    id: 18,
    gameName: "uno",
    type: "number",
    data: { dataId: 18, color: "red", text: "9" },
  },
  19: {
    id: 19,
    gameName: "uno",
    type: "number",
    data: { dataId: 19, color: "red", text: "9" },
  },

  20: {
    id: 20,
    gameName: "uno",
    type: "number",
    data: { dataId: 20, color: "green", text: "0" },
  },
  21: {
    id: 21,
    gameName: "uno",
    type: "number",
    data: { dataId: 21, color: "green", text: "1" },
  },
  22: {
    id: 22,
    gameName: "uno",
    type: "number",
    data: { dataId: 22, color: "green", text: "1" },
  },
  23: {
    id: 23,
    gameName: "uno",
    type: "number",
    data: { dataId: 23, color: "green", text: "2" },
  },
  24: {
    id: 24,
    gameName: "uno",
    type: "number",
    data: { dataId: 24, color: "green", text: "2" },
  },
  25: {
    id: 25,
    gameName: "uno",
    type: "number",
    data: { dataId: 25, color: "green", text: "3" },
  },
  26: {
    id: 26,
    gameName: "uno",
    type: "number",
    data: { dataId: 26, color: "green", text: "3" },
  },
  27: {
    id: 27,
    gameName: "uno",
    type: "number",
    data: { dataId: 27, color: "green", text: "4" },
  },
  28: {
    id: 28,
    gameName: "uno",
    type: "number",
    data: { dataId: 28, color: "green", text: "4" },
  },
  29: {
    id: 29,
    gameName: "uno",
    type: "number",
    data: { dataId: 29, color: "green", text: "5" },
  },
  30: {
    id: 30,
    gameName: "uno",
    type: "number",
    data: { dataId: 30, color: "green", text: "5" },
  },
  31: {
    id: 31,
    gameName: "uno",
    type: "number",
    data: { dataId: 31, color: "green", text: "6" },
  },
  32: {
    id: 32,
    gameName: "uno",
    type: "number",
    data: { dataId: 32, color: "green", text: "6" },
  },
  33: {
    id: 33,
    gameName: "uno",
    type: "number",
    data: { dataId: 33, color: "green", text: "7" },
  },
  34: {
    id: 34,
    gameName: "uno",
    type: "number",
    data: { dataId: 34, color: "green", text: "7" },
  },
  35: {
    id: 35,
    gameName: "uno",
    type: "number",
    data: { dataId: 35, color: "green", text: "8" },
  },
  36: {
    id: 36,
    gameName: "uno",
    type: "number",
    data: { dataId: 36, color: "green", text: "8" },
  },
  37: {
    id: 37,
    gameName: "uno",
    type: "number",
    data: { dataId: 37, color: "green", text: "9" },
  },
  38: {
    id: 38,
    gameName: "uno",
    type: "number",
    data: { dataId: 38, color: "green", text: "9" },
  },

  39: {
    id: 39,
    gameName: "uno",
    type: "number",
    data: { dataId: 39, color: "yellow", text: "0" },
  },
  40: {
    id: 40,
    gameName: "uno",
    type: "number",
    data: { dataId: 40, color: "yellow", text: "1" },
  },
  41: {
    id: 41,
    gameName: "uno",
    type: "number",
    data: { dataId: 41, color: "yellow", text: "1" },
  },
  42: {
    id: 42,
    gameName: "uno",
    type: "number",
    data: { dataId: 42, color: "yellow", text: "2" },
  },
  43: {
    id: 43,
    gameName: "uno",
    type: "number",
    data: { dataId: 43, color: "yellow", text: "2" },
  },
  44: {
    id: 44,
    gameName: "uno",
    type: "number",
    data: { dataId: 44, color: "yellow", text: "3" },
  },
  45: {
    id: 45,
    gameName: "uno",
    type: "number",
    data: { dataId: 45, color: "yellow", text: "3" },
  },
  46: {
    id: 46,
    gameName: "uno",
    type: "number",
    data: { dataId: 46, color: "yellow", text: "4" },
  },
  47: {
    id: 47,
    gameName: "uno",
    type: "number",
    data: { dataId: 47, color: "yellow", text: "4" },
  },
  48: {
    id: 48,
    gameName: "uno",
    type: "number",
    data: { dataId: 48, color: "yellow", text: "5" },
  },
  49: {
    id: 49,
    gameName: "uno",
    type: "number",
    data: { dataId: 49, color: "yellow", text: "5" },
  },
  50: {
    id: 50,
    gameName: "uno",
    type: "number",
    data: { dataId: 50, color: "yellow", text: "6" },
  },
  51: {
    id: 51,
    gameName: "uno",
    type: "number",
    data: { dataId: 51, color: "yellow", text: "6" },
  },
  52: {
    id: 52,
    gameName: "uno",
    type: "number",
    data: { dataId: 52, color: "yellow", text: "7" },
  },
  53: {
    id: 53,
    gameName: "uno",
    type: "number",
    data: { dataId: 53, color: "yellow", text: "7" },
  },
  54: {
    id: 54,
    gameName: "uno",
    type: "number",
    data: { dataId: 54, color: "yellow", text: "8" },
  },
  55: {
    id: 55,
    gameName: "uno",
    type: "number",
    data: { dataId: 55, color: "yellow", text: "8" },
  },
  56: {
    id: 56,
    gameName: "uno",
    type: "number",
    data: { dataId: 56, color: "yellow", text: "9" },
  },
  57: {
    id: 57,
    gameName: "uno",
    type: "number",
    data: { dataId: 57, color: "yellow", text: "9" },
  },

  58: {
    id: 58,
    gameName: "uno",
    type: "number",
    data: { dataId: 58, color: "blue", text: "0" },
  },
  59: {
    id: 59,
    gameName: "uno",
    type: "number",
    data: { dataId: 59, color: "blue", text: "1" },
  },
  60: {
    id: 60,
    gameName: "uno",
    type: "number",
    data: { dataId: 60, color: "blue", text: "1" },
  },
  61: {
    id: 61,
    gameName: "uno",
    type: "number",
    data: { dataId: 61, color: "blue", text: "2" },
  },
  62: {
    id: 62,
    gameName: "uno",
    type: "number",
    data: { dataId: 62, color: "blue", text: "2" },
  },
  63: {
    id: 63,
    gameName: "uno",
    type: "number",
    data: { dataId: 63, color: "blue", text: "3" },
  },
  64: {
    id: 64,
    gameName: "uno",
    type: "number",
    data: { dataId: 64, color: "blue", text: "3" },
  },
  65: {
    id: 65,
    gameName: "uno",
    type: "number",
    data: { dataId: 65, color: "blue", text: "4" },
  },
  66: {
    id: 66,
    gameName: "uno",
    type: "number",
    data: { dataId: 66, color: "blue", text: "4" },
  },
  67: {
    id: 67,
    gameName: "uno",
    type: "number",
    data: { dataId: 67, color: "blue", text: "5" },
  },
  68: {
    id: 68,
    gameName: "uno",
    type: "number",
    data: { dataId: 68, color: "blue", text: "5" },
  },
  69: {
    id: 69,
    gameName: "uno",
    type: "number",
    data: { dataId: 69, color: "blue", text: "6" },
  },
  70: {
    id: 70,
    gameName: "uno",
    type: "number",
    data: { dataId: 70, color: "blue", text: "6" },
  },
  71: {
    id: 71,
    gameName: "uno",
    type: "number",
    data: { dataId: 71, color: "blue", text: "7" },
  },
  72: {
    id: 72,
    gameName: "uno",
    type: "number",
    data: { dataId: 72, color: "blue", text: "7" },
  },
  73: {
    id: 73,
    gameName: "uno",
    type: "number",
    data: { dataId: 73, color: "blue", text: "8" },
  },
  74: {
    id: 74,
    gameName: "uno",
    type: "number",
    data: { dataId: 74, color: "blue", text: "8" },
  },
  75: {
    id: 75,
    gameName: "uno",
    type: "number",
    data: { dataId: 75, color: "blue", text: "9" },
  },
  76: {
    id: 76,
    gameName: "uno",
    type: "number",
    data: { dataId: 76, color: "blue", text: "9" },
  },

  77: {
    id: 77,
    gameName: "uno",
    type: "+2",
    data: { dataId: 77, color: "red", text: "+2" },
  },
  78: {
    id: 78,
    gameName: "uno",
    type: "+2",
    data: { dataId: 78, color: "red", text: "+2" },
  },
  79: {
    id: 79,
    gameName: "uno",
    type: "+2",
    data: { dataId: 79, color: "green", text: "+2" },
  },
  80: {
    id: 80,
    gameName: "uno",
    type: "+2",
    data: { dataId: 80, color: "green", text: "+2" },
  },
  81: {
    id: 81,
    gameName: "uno",
    type: "+2",
    data: { dataId: 81, color: "yellow", text: "+2" },
  },
  82: {
    id: 82,
    gameName: "uno",
    type: "+2",
    data: { dataId: 82, color: "yellow", text: "+2" },
  },
  83: {
    id: 83,
    gameName: "uno",
    type: "+2",
    data: { dataId: 83, color: "blue", text: "+2" },
  },
  84: {
    id: 84,
    gameName: "uno",
    type: "+2",
    data: { dataId: 84, color: "blue", text: "+2" },
  },

  85: {
    id: 85,
    gameName: "uno",
    type: "reverse",
    data: { dataId: 85, color: "red", text: "reverse" },
  },
  86: {
    id: 86,
    gameName: "uno",
    type: "reverse",
    data: { dataId: 86, color: "red", text: "reverse" },
  },
  87: {
    id: 87,
    gameName: "uno",
    type: "reverse",
    data: { dataId: 87, color: "green", text: "reverse" },
  },
  88: {
    id: 88,
    gameName: "uno",
    type: "reverse",
    data: { dataId: 88, color: "green", text: "reverse" },
  },
  89: {
    id: 89,
    gameName: "uno",
    type: "reverse",
    data: { dataId: 89, color: "yellow", text: "reverse" },
  },
  90: {
    id: 90,
    gameName: "uno",
    type: "reverse",
    data: { dataId: 90, color: "yellow", text: "reverse" },
  },
  91: {
    id: 91,
    gameName: "uno",
    type: "reverse",
    data: { dataId: 91, color: "blue", text: "reverse" },
  },
  92: {
    id: 92,
    gameName: "uno",
    type: "reverse",
    data: { dataId: 92, color: "blue", text: "reverse" },
  },

  93: {
    id: 93,
    gameName: "uno",
    type: "skip",
    data: { dataId: 93, color: "red", text: "skip" },
  },
  94: {
    id: 94,
    gameName: "uno",
    type: "skip",
    data: { dataId: 94, color: "red", text: "skip" },
  },
  95: {
    id: 95,
    gameName: "uno",
    type: "skip",
    data: { dataId: 95, color: "green", text: "skip" },
  },
  96: {
    id: 96,
    gameName: "uno",
    type: "skip",
    data: { dataId: 96, color: "green", text: "skip" },
  },
  97: {
    id: 97,
    gameName: "uno",
    type: "skip",
    data: { dataId: 97, color: "yellow", text: "skip" },
  },
  98: {
    id: 98,
    gameName: "uno",
    type: "skip",
    data: { dataId: 98, color: "yellow", text: "skip" },
  },
  99: {
    id: 99,
    gameName: "uno",
    type: "skip",
    data: { dataId: 99, color: "blue", text: "skip" },
  },
  100: {
    id: 100,
    gameName: "uno",
    type: "skip",
    data: { dataId: 100, color: "blue", text: "skip" },
  },

  101: {
    id: 101,
    gameName: "uno",
    type: "joker",
    data: { dataId: 101, color: "custom", text: "joker" },
  },
  102: {
    id: 102,
    gameName: "uno",
    type: "joker",
    data: { dataId: 102, color: "custom", text: "joker" },
  },
  103: {
    id: 103,
    gameName: "uno",
    type: "joker",
    data: { dataId: 103, color: "custom", text: "joker" },
  },
  104: {
    id: 104,
    gameName: "uno",
    type: "joker",
    data: { dataId: 104, color: "custom", text: "joker" },
  },

  105: {
    id: 105,
    gameName: "uno",
    type: "+4",
    data: { dataId: 105, color: "custom", text: "+4" },
  },
  106: {
    id: 106,
    gameName: "uno",
    type: "+4",
    data: { dataId: 106, color: "custom", text: "+4" },
  },
  107: {
    id: 107,
    gameName: "uno",
    type: "+4",
    data: { dataId: 107, color: "custom", text: "+4" },
  },
  108: {
    id: 108,
    gameName: "uno",
    type: "+4",
    data: { dataId: 108, color: "custom", text: "+4" },
  },
};
